# This is a basic workflow to help you get started with Actions

name: Workflow Commands

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Start of logs"
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::group::My title"
          echo "Inside group"
          for i in $(seq 1 10);
          do
            echo $i
            sleep 1
          done
          echo "::endgroup::"
          echo "::group::Levels without workflow commands"
          echo "[ERROR] An error without using the workflow command"
          echo "[WARN] A warning without using the workflow command"
          echo "[WARNING] A warning without using the workflow command"
          echo "[INFO] A regular log message"
          echo "[NOTICE] A notice without using the workflow command"
          echo "[DEBUG] A debug message without using the workflow command"
          echo "::endgroup::"
          echo "::group::Keyword detection"
          echo "An ERROR without using the workflow command"
          echo "A FAILURE without using the workflow command"
          echo "A FAILED command without using the workflow command"
          echo "A WARN message without using the workflow command"
          echo "A WARNING without using the workflow command"
          echo "An INFO log message"
          echo "A NOTICE without using the workflow command"
          echo "A DEBUG message without using the workflow command"
          echo "An error without using the workflow command"
          echo "A failure without using the workflow command"
          echo "A failed command without using the workflow command"
          echo "A warn message without using the workflow command"
          echo "A warning without using the workflow command"
          echo "An info log message"
          echo "A notice without using the workflow command"
          echo "A debug message without using the workflow command"
          echo "::endgroup::"
          echo "::warning::1
          2
          3"
          echo "End of logs"
